### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by Ernestopheles** [Bobface/aurad-utils#1]
Hi Bobface,

I am missing a notification when your Software changes. Watching this side did not work as there were no new conversations and no new release either.

Thanks

**Comment by Bobface** [comment]
When the script is running it says if it is up to date in the first line ("Script is up to date"). If it says "A new version of this script is available ... " then theres an update available.

**Comment by Bobface** [comment]
I'll close this now, if you have further questions you can contact me via Discord :)
