### ISSUE TITLE
Run aurad-status.py in systemd

### ISSUE THREAD

**Issue by bneiluj** [Bobface/aurad-utils#2]
I'm not sure but at first look it looks like aurad-status.py doesn't run in the background. I couldn't find any nohup or systemd command.

**Comment by Bobface** [comment]
That's correct, on its own it's just a python script. 
I recommend to use `screen` (which is preinstalled on many distros) to run it in the background. 

A screen is like a container in which a program can run and continues to run even when you close the connection to your server/machine. You first need to start a screen with `screen -S <NAME>`, then run aurad-status inside there. You can detach from the screen by `CTRL + A + D`. When you want to re-attach to it, type `screen -r <NAME>`
