### ISSUE TITLE
Adding monitor to scripts

### ISSUE THREAD

**Issue by sajklan** [Bobface/aurad-utils#3]
Hi,

Is it possible to add the same Pushbullets notifications to your script? So It send a notice when it's down
Like this https://busy.org/@dillagr/masternode-proof-of-stake-push-notifications

**Comment by Bobface** [comment]
Hi, I am currently not really working on this script anymore. I hope that it can be of use for you as it is now.

**Comment by sajklan** [comment]
I'm sorry I didn't mean for you to do it, more guiding me ;) I've been playing around with it, but not sure where to put push notice command
